<?php 
return array (
  'ver_name' => 'YxcmsApp 1.3.1',
  'ver_date' => '20150817',
  'copyright' => '由wang提供技术支持',
  'sitename' => '我的网站',
  'siteurl' => 'http://admin.wangjinhao.cn',
  'title' => '测试页面',
  'keywords' => 'jhahkji',
  'desc' => '发热',
  'sitestatus' => '0',
  'sitestatus_detail' => '',
  'mobile' => '18211674978',
  'QQ' => '123456',
  'email' => '2880326171@qq.com',
  'address' => 'your address',
  'seo_title' => 'cms ',
  'seo_keywords' => 'yii2',
  'seo_desc' => '',
  'seo_other' => '',
  'icp' => 'ICPxxxxxx',
  'fileupSize' => '9000000000',
  'imgupSize' => 70000000,
  'ifwatermark' => true,
  'watermarkImg' => 'logo.png',
  'watermarkPlace' => 9,
  'sortMaxwidth' => 300,
  'sortMaxheight' => 300,
  'coverMaxwidth' => 225,
  'coverMaxheight' => 76,
  'thumbMaxwidth' => 271,
  'thumbMaxheight' => 271,
  'allowType' => 'jpg,bmp,gif,png,flv,mp4,mp3,wma,mp4,7z,zip,rar,ppt,txt,pdf,xls,doc,swf,wmv,avi,rmvb,rm',
  'submit' => '',
  'addreess' => 'your address',
  '_csrf' => 'THo4UUpwRnQDSGs.JCYlMS8wQis4NXIePhYBDhtHCQIqTkIackl.Ag==',
  'mail_type' => '1',
  'page' => '1',
  'post' => '2',
);